### ISSUE TITLE
Crash on start ('ascii' codec can't encode characters in position 0-8)

### ISSUE THREAD

**Issue by NewFolk** [Anthirian/script.service.janitor#55]
Kodi-17.1 (osmc edition)
latest plugin from official repo (4.3.0)

```
14:11:11.907 T:1378874352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.service.janitor/default.py", line 646, in <module>
                                                results, return_status = cleaner.clean_all()
                                              File "/home/osmc/.kodi/addons/script.service.janitor/default.py", line 228, in clean_all
                                                cleaned_files, count, status = self.clean(video_type)
                                              File "/home/osmc/.kodi/addons/script.service.janitor/default.py", line 193, in clean
                                                title = title.encode()
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
                                            -->End of Python script error report<--
14:11:12.186 T:1378874352 WARNING: CPythonInvoker(9, /home/osmc/.kodi/addons/script.service.janitor/default.py): the python script "/home/osmc/.kodi/addons/script.service.janitor/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE,N9XBMCAddon4xbmc7MonitorE
```

PS everything works good before update. On Kodi 16.x and Janitor 4.2.1

**Comment by Anthirian** [comment]
Thanks for your bug report. It would appear I broke something while optimizing my code for Jarvis. Would you mind changing the `title = title.encode()` mentioned in the stack trace to `title = title.encode("utf-8")` and try again? I'm suspecting the default behavior for the `encode()` function is different than I anticipated.

**Comment by NewFolk** [comment]
Looks like it helps. Thank you!

**Comment by Anthirian** [comment]
Allright, thanks for letting me know. I'll be reverting those changes in a bug fix release soon. In the meantime if you encounter similar errors in different areas, you can apply the same fix.
